## Helpers that drive imported animations the way Blitz3D did (convention C2):
## the game never plays animations, it seeks them to a frame every tick.
class_name BlitzAnimator
extends RefCounted

const B3D_ANIMATION := "b3d"
const MD2_ANIMATION := "md2"
## Blitz adds `alpha * colour` in gamma space, Godot in linear space; the converter raises
## the alpha of additive brushes to this power (`blitzconv.ADDITIVE_ALPHA_EXPONENT`) and
## runtime alphas (EntityAlpha, ANIMBRUSH keys) follow the same rule.
const ADDITIVE_ALPHA_EXPONENT := 1.5
const BLEND_ADD := 3


## Alpha factor as the converter would have written it for material `m`.
static func blend_alpha(m: Material, alpha: float) -> float:
	return _blend_alpha(is_additive(m), alpha)


static func _blend_alpha(additive: bool, alpha: float) -> float:
	var a := clampf(alpha, 0.0, 1.0)
	return pow(a, ADDITIVE_ALPHA_EXPONENT) if additive else a


static func is_additive(m: Material) -> bool:
	return m.has_meta("blitz_blend") and int(m.get_meta("blitz_blend")) == BLEND_ADD


static func find_player(root: Node) -> AnimationPlayer:
	if root == null:
		return null
	for c in root.get_children():
		if c is AnimationPlayer:
			return c
	return root.find_child("AnimationPlayer", true, false) as AnimationPlayer


## Find the first MeshInstance3D under `root` (MD2 models have exactly one).
static func find_mesh(root: Node) -> MeshInstance3D:
	if root is MeshInstance3D:
		return root
	for c in root.get_children():
		var m := find_mesh(c)
		if m != null:
			return m
	return null


## Blitz `SetAnimTime(entity, t)`: 1 Blitz frame = 1.0 s of the imported animation.
static func seek(player: AnimationPlayer, t: float, animation: String = B3D_ANIMATION) -> void:
	if player == null:
		return
	if player.assigned_animation != animation:
		player.assigned_animation = animation
	player.seek(t, true)


## Blitz `AnimateMD2` loop display: frame a = floor(t), b = a + 1, but b wraps to `first`
## when it reaches `last` (MD2Model::update: `render_b == anim_last -> anim_first`).
## Blend shape k corresponds to frame k (frame 0 is the base mesh).
static func md2_frame(mesh: MeshInstance3D, t: float, first: int = 0, last: int = 10) -> void:
	if mesh == null:
		return
	var count := mesh.get_blend_shape_count()
	var a := int(floorf(t))
	var b := a + 1
	if b >= last:
		b = first
	var f := t - floorf(t)
	for k in count:
		var frame := k + 1
		var w := 0.0
		if frame == a:
			w += 1.0 - f
		if frame == b:
			w += f
		mesh.set_blend_shape_value(k, w)


## Brush colour of a material: StandardMaterial3D albedo or the `albedo` uniform of the
## sphere-mapped ShaderMaterial generated by the importer.
static func material_color(m: Material) -> Color:
	if m is StandardMaterial3D:
		return (m as StandardMaterial3D).albedo_color
	if m is ShaderMaterial:
		var v = (m as ShaderMaterial).get_shader_parameter("albedo")
		return v if v is Color else Color.WHITE
	return Color.WHITE


## The importer gives alpha-textured brushes a second, alpha-scissored pass that writes the
## depth of their solid texels (`b3d_post_import.gd` `solid_pass`); every change to the
## brush state is applied to both passes so the solid pass never shows through with a
## stale colour, alpha, texture or scroll.
static func _solid_pass(m: Material) -> StandardMaterial3D:
	if m is StandardMaterial3D:
		return (m as StandardMaterial3D).next_pass as StandardMaterial3D
	return null


static func set_material_color(m: Material, c: Color) -> void:
	if m is StandardMaterial3D:
		(m as StandardMaterial3D).albedo_color = c
		var solid := _solid_pass(m)
		if solid != null:
			solid.albedo_color = c
	elif m is ShaderMaterial:
		(m as ShaderMaterial).set_shader_parameter("albedo", c)


static func set_material_uv_offset(m: Material, offset: Vector3) -> void:
	if m is StandardMaterial3D:
		(m as StandardMaterial3D).uv1_offset = offset
		var solid := _solid_pass(m)
		if solid != null:
			solid.uv1_offset = offset
	elif m is ShaderMaterial:
		(m as ShaderMaterial).set_shader_parameter("uv1_offset", offset)


## Replace the first texture layer (`EntityTexture` on a one-layer brush).
static func set_material_texture(m: Material, texture: Texture2D) -> void:
	if m is StandardMaterial3D:
		(m as StandardMaterial3D).albedo_texture = texture
		var solid := _solid_pass(m)
		if solid != null:
			solid.albedo_texture = texture
	elif m is ShaderMaterial:
		(m as ShaderMaterial).set_shader_parameter("layer0", texture)


static func _is_blitz_material(m: Material) -> bool:
	return m is StandardMaterial3D or m is ShaderMaterial


## Copy of a Blitz material for per-instance changes; the solid pass is copied with it
## (`Resource.duplicate` would keep sharing it with every other instance).
static func copy_material(m: Material) -> Material:
	var own := m.duplicate() as Material
	var solid := _solid_pass(own)
	if solid != null:
		(own as StandardMaterial3D).next_pass = solid.duplicate()
	return own


## Per-instance copy of surface `i` of `mi` (made once, marked "owned").
static func owned_material(mi: MeshInstance3D, i: int) -> Material:
	var own := mi.get_surface_override_material(i)
	if own == null or not own.has_meta("owned"):
		own = copy_material(mi.get_active_material(i))
		own.set_meta("owned", true)
		mi.set_surface_override_material(i, own)
	return own


## Per-instance copies of every Blitz material under `root`, in one tree walk. Views that
## recolour every tick keep this list instead of walking their model again.
static func owned_materials(root: Node) -> Array[Material]:
	var out: Array[Material] = []
	for mi in _meshes(root):
		for i in mi.get_surface_override_material_count():
			if _is_blitz_material(mi.get_active_material(i)):
				out.append(owned_material(mi, i))
	return out


## Blitz `EntityColor` (`_fentitycolor_`) on the materials of `owned_materials`: the RGB
## changes, the alpha stays.
static func tint_materials(mats: Array[Material], color: Color) -> void:
	for m in mats:
		set_material_color(m, Color(color.r, color.g, color.b, material_color(m).a))


## Blitz `EntityColor` applied recursively (`_fentitycolor_`): tints every material.
## Materials are duplicated once per instance so tinting does not leak between copies.
static func tint(root: Node, color: Color) -> void:
	tint_materials(owned_materials(root), color)


## What `set_alpha_entries` needs per surface of `root`: the instance's material copy, the
## brush alpha of the mesh's own material and whether that brush blends additively.
static func alpha_entries(root: Node) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for mi in _meshes(root):
		for i in mi.get_surface_override_material_count():
			var base := mi.mesh.surface_get_material(i) if mi.mesh != null else null
			if base == null or not _is_blitz_material(base):
				continue
			out.append({"material": owned_material(mi, i), "base_alpha": material_color(base).a, "additive": is_additive(base)})
	return out


## Blitz `EntityAlpha` (`_fentityalpha_`) on the entries of `alpha_entries`: the brush
## alpha of the mesh's own material times `alpha`.
static func set_alpha_entries(entries: Array[Dictionary], alpha: float) -> void:
	for e in entries:
		var m: Material = e["material"]
		var c := material_color(m)
		c.a = float(e["base_alpha"]) * _blend_alpha(bool(e["additive"]), alpha)
		set_material_color(m, c)


## Blitz `EntityAlpha` applied recursively (`_fentityalpha_`).
static func set_alpha(root: Node, alpha: float) -> void:
	set_alpha_entries(alpha_entries(root), alpha)


static func _meshes(root: Node) -> Array[MeshInstance3D]:
	var out: Array[MeshInstance3D] = []
	if root is MeshInstance3D:
		out.append(root)
	for c in root.get_children():
		out.append_array(_meshes(c))
	return out


## B3D Extensions animated texture maps (`B3DEXT_ANIMMAP` + `B3DEXT_UVPOS`): returns a
## list of {"uvpos": Node3D, "materials": [StandardMaterial3D]} with per-instance material
## copies, to be fed to `update_animmaps()` after every seek.
static func setup_animmaps(root: Node) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for n in root.find_children("B3DEXT_ANIMMAP*", "Node3D", true, false):
		if not n.has_meta("blitz_animmap_material"):
			continue
		var uvpos: Node3D = n.find_child("B3DEXT_UVPOS*", true, false)
		if uvpos == null:
			continue
		var entry := {"uvpos": uvpos, "materials": _owned_materials(root, n.get_meta("blitz_animmap_material"))}
		# The UVPOS position track, so the map can be sampled at a frame other than the
		# model's own (`_fupdateextanims` drives a tower type's shared texture from one tower).
		var player := find_player(root)
		if player != null and player.has_animation(B3D_ANIMATION):
			var anim := player.get_animation(B3D_ANIMATION)
			var path := NodePath(str(player.get_node(player.root_node).get_path_to(uvpos)))
			var track := anim.find_track(path, Animation.TYPE_POSITION_3D)
			if track >= 0:
				entry["animation"] = anim
				entry["track"] = track
		out.append(entry)
	return out


## B3D Extensions animated brushes (`B3DEXT_ANIMBRUSH` + `B3DEXT_ALPHA` / `B3DEXT_COLOR`):
## the child's position keys are the brush alpha (x) / colour (x, z, y) per frame
## (`_fext_updateanimbrushes`). Returns entries for `update_animbrushes`.
static func setup_animbrushes(root: Node) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for n in root.find_children("B3DEXT_ANIMBRUSH*", "Node3D", true, false):
		if not n.has_meta("blitz_animbrush_material"):
			continue
		var alpha: Node3D = n.find_child("B3DEXT_ALPHA*", true, false)
		var color: Node3D = n.find_child("B3DEXT_COLOR*", true, false)
		if alpha == null and color == null:
			continue
		out.append({"alpha": alpha, "color": color, "materials": _owned_materials(root, n.get_meta("blitz_animbrush_material"))})
	return out


static func update_animbrushes(brushes: Array[Dictionary]) -> void:
	for entry in brushes:
		for m in entry["materials"]:
			var c := material_color(m)
			if entry["color"] != null:
				var p: Vector3 = (entry["color"] as Node3D).position
				c = Color(p.x, -p.z, p.y, c.a)  # Blitz (x, z, y) with the mirrored z
			if entry["alpha"] != null:
				c.a = blend_alpha(m, (entry["alpha"] as Node3D).position.x)
			set_material_color(m, c)


## Per-instance copies of every surface material named `mat_name` under `root`.
static func _owned_materials(root: Node, mat_name: String) -> Array:
	var mats: Array = []
	for mi in _meshes(root):
		for i in mi.get_surface_override_material_count():
			var m := mi.get_active_material(i)
			if _is_blitz_material(m) and m.resource_name == mat_name:
				mats.append(owned_material(mi, i))
	return mats


## Blitz `PositionTexture(-x, -y)` semantics: the UVPOS key is the negated UV offset
## (sphere-mapped layers ignore it, as their texture matrix is the sphere map).
## With `frame >= 0` the UVPOS keys are sampled at that frame instead of the node's
## current (seeked) position.
static func update_animmaps(maps: Array[Dictionary], frame := -1.0) -> void:
	for entry in maps:
		var p: Vector3 = (entry["uvpos"] as Node3D).position
		if frame >= 0.0 and entry.has("track"):
			p = (entry["animation"] as Animation).position_track_interpolate(entry["track"], frame)
		for m in entry["materials"]:
			set_material_uv_offset(m, Vector3(-p.x, -p.y, 0.0))


## Hide the B3DEXT_* tag nodes and editor cameras that exist only for the loader.
static func hide_helpers(root: Node) -> void:
	for n in root.find_children("*", "Node3D", true, false):
		if n.name.begins_with("B3DEXT_") or n.name.begins_with("Camera0") or n.name == "CamPath":
			(n as Node3D).visible = false
