"""The Defold port's backend: the Defold project's generated resources.

Reads the import stage's tree (tools/source_import.py: glb models with `.b3d.json`
sidecars, textures, the game tables, the launcher icons) and the original's sounds, and
writes into the Defold project:

- `assets/models/*.glb`, `generated/materials/*`, `generated/models/*.model`,
  `generated/go/*.go` -- the location scenes, the towers, bullets, effects, the monsters
  and the HUD panel (see models.py);
- `assets/textures/...`, `assets/audio/...` -- the textures and sounds they use;
- `assets/hud/` -- the GUI atlas cut from `gui.png` (hud.py);
- `generated/icons/`, `generated/bundle/` -- the launcher icons (icons.py);
- `data/*.json` -- the game tables (custom resources);
- `generated/locations/l<N>.lua` (+ the `generated/locations.lua` index) -- per location:
  camera bounds, background colour, scene light, tower tint, music, build zones;
- `generated/collections/location<N>.collection` -- a location's scene plus the location
  screen's game objects (main/location/), loaded by a collection proxy;
- `generated/render_passes.lua` -- the draw passes, the union over every scene, and the
  passes each screen's materials match;
- `generated/common.lua` -- the health bar gradient;
- `generated/models.lua` -- per model: game object, animation length, groups, ANIMMAP keys;
- `generated/entities.go` -- one factory per model;
- `generated/sounds.go` -- one sound component per file (groups `music` / `sfx`).

Run through tools/build_assets.py (`make defold`).
"""
from __future__ import annotations

import json
import logging
import math
import re
import shutil
from pathlib import Path

from PIL import Image

from audio import audio_sources, encode_ffmpeg_vorbis, encode_vorbis, transcode_wav, wav_info
from gltfwriter import read_accessor, read_glb
from mat4 import mat_mul, node_matrix, quat_rotate, rigid_pose, transform_point, unit_normal

from .hud import export_gradient, export_hud_atlas
from .icons import export_icons
from .hud_layout import MODEL_RULES as HUD_ANCHORS
from .materials import fmt, order_tag
from .models import ModelExporter, load_sidecar

LOG = logging.getLogger("targets.defold")
GENERATED_HEADER = "-- Generated by tools/build_assets.py -- do not edit."
ROOT = Path(__file__).resolve().parents[3]

ZONE_NODES = ["grass", "road", "noparking", "rocks"]
TOWER_MODELS = ["Military", "Magic", "Nature", "Freeze", "Fire"]
TOWER_EXTRAS = ["MilitaryPlace", "MagicPlace", "NaturePlace", "FreezePlace", "FirePlace",
                "MilitaryEff", "MagicEff", "NatureEff", "FreezeEff", "PoisonEff",
                "range", "selection", "selmonster", "shadow", "death", "Balloon", "here"]
BULLET_MODELS = [f"{t}{i}" for t in ("military", "magic", "nature", "freeze") for i in range(1, 6)]
ROOT_MODELS = ["health", "Env", "faces"]
HUD_MODELS = ("Env", "faces")
# The HUD camera in the panel's own space (`MoveEntity(env, 0, 0, 10)`, main/location/world.lua
# PANEL_OFFSET): the panel's translucent nodes are drawn farthest from it first.
HUD_PANEL = "Env"
HUD_PANEL_EYE = (0.0, 0.0, 10.0)
DATA_FILES = ["units.json", "towers.json", "raids.json", "paths.json", "locations.json", "texts.json", "hud_layout.json"]
# The 3D menu scenes (`Menu/*.b3d`, docs/09). The sheets hang on the camera 10 units in front
# of it, so they are drawn by the fixed overlay camera like the HUD panel; they are
# bone-posed so the runtime can pick, hide and follow their nodes. `node_groups`: nodes
# whose texture or colour changes at runtime.
MENU_SHEETS = {
    "Menu/buttons": ("titul",), "Menu/playgame": (), "Menu/credits": (), "Menu/loading": (), "Menu/sel": (),
    "Menu/congr": (), "Menu/gameover": (), "Menu/ingame": (), "Menu/music": (), "Menu/sound": (),
    "Menu/highscores": (), "Menu/Send": (), "Menu/SendTD": (),
    "Menu/map": ("titul", "point1", "point2", "point3", "point4", "point5", "point6"),
    "Additional/end": (), "tutorial": (),
}
# EntityOrders the game sets at run time (`_floadmenu`): the loading sheet's black
# curtain and plank are drawn over the menu without the z-buffer.
SHEET_ORDERS = {"Menu/loading": {"fon": -5, "loading": -6}}
# The main menu's world: the castle scene and the animated camera carrying the sky.
MENU_WORLD = ["Menu/env"]
MENU_CAMERA = "Menu/cameraEnv"
MENU_CAMERA_NODE = "Camera01"
# B3D Extensions cameras look along the node's local -Y with its +Z up (the Godot port's
# MainMenu.CAMERA_FIX): camera basis (x, y, z) = node (x, -z, y).
CAMERA_FIX = [[1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, -1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
# Per-location decorations (`_fdecoratelocation`, `_fhandledecorates`): location 1's clock
# hands (game objects the runtime turns: role -> node), location 2's eagle on its bird path,
# location 2's water loop at the `door` node (`EmitSound`).
CLOCK_HANDS = {1: {"hours": "little_arrow", "minutes": "big_arrow", "seconds": "second_arrow"}}
EAGLE = {2: {"path": "Location1/birdpath1", "node": "piv", "model": "Additional/eagle"}}
WATER_EMITTER = {2: "door"}
# Textures no model references that the runtime sets: the menu title per unlocked
# difficulty, the loading plank.
RUNTIME_TEXTURES = ["Menu/Titul1.png", "Menu/Titul2.png", "Menu/Titul3.png"]
# Sound groups (sound.set_group_gain): the music and effects volume settings.
SOUND_GROUP_MUSIC, SOUND_GROUP_SFX = "music", "sfx"
LOOPED_SOUNDS = ("tlen", "water")
# The project's own (hand-written) resources, next to the exported ones.
PROJECT_DIR = ROOT / "defold"
# The Defold project's directories the export owns (all gitignored): emptied before every
# run, so nothing an older export wrote (a renamed model, fewer materials, a texture no model
# uses any more) outlives it.
OUTPUT_DIRS = ("assets", "generated", "data")
EXPORTED_DIRS = ("/generated/", "/assets/")
# The screens: the collections the controller loads through its collection proxies.
CONTROLLER_GO = "/main/controller.go"
PROXY_COLLECTION = re.compile(r'collection: \\"(/[\w./-]+\.collection)\\"')
# A reference to a resource: any component, sub-collection, factory prototype or material
# can bring materials into a screen. Binary assets are not read for further references.
RESOURCE_REFERENCE = re.compile(r"(/[\w./-]+\.\w+)")
BINARY_RESOURCES = (".glb", ".gltf", ".png", ".jpg", ".jpeg", ".wav", ".ogg", ".bin", ".ttf", ".otf")
MATERIAL_TAG = re.compile(r'^tags: "([^"]+)"', re.M)
COLLECTION_NAME = re.compile(r'^name: "([^"]+)"', re.M)


# `_fext_initlight` for a B3DEXT_OMNILIGHT tag: CreateLight(2) at the tag's parent, colour
# `LightColor(x, z, y)` of the tag's position (x255 mod 256, `_fext_linklightcolor`). No
# scene sets B3DEXT_RANGE, so the range stays Blitz's default (gxlight.cpp `setRange(1000)`).
OMNILIGHT_TAG = "B3DEXT_OMNILIGHT"
BLITZ_LIGHT_RANGE = 1000.0
MAX_POINT_LIGHTS = 2  # the lit shaders' `point_light0` / `point_light1`


def point_lights(doc: dict) -> list[dict]:
    """The scene's omni lights: world position (glTF), range and RGB (0..1)."""
    nodes = doc["nodes"]
    parents = {c: i for i, n in enumerate(nodes) for c in n.get("children", [])}
    out = []
    for i, node in enumerate(nodes):
        if not node.get("name", "").startswith(OMNILIGHT_TAG) or i not in parents:
            continue
        world = node_matrix(nodes[parents[i]])
        j = parents[i]
        while j in parents:
            j = parents[j]
            world = mat_mul(node_matrix(nodes[j]), world)
        # glTF z is Blitz's -z (tools/b3d2gltf.py).
        x, y, z = node.get("translation", [0.0, 0.0, 0.0])
        color = [max(0.0, math.fmod(255.0 * c, 256.0)) / 255.0 for c in (x, -z, y)]
        out.append({"position": list(transform_point(world, (0.0, 0.0, 0.0))), "range": BLITZ_LIGHT_RANGE, "color": color})
    if len(out) > MAX_POINT_LIGHTS:
        raise ValueError(f"{len(out)} omni lights, the shaders take {MAX_POINT_LIGHTS}")
    return out


TEXTURE_BLOCK = 4  # BC/ASTC-4x4/UASTC block side the compressed texture profiles need
JPEG_QUALITY = 95  # a re-saved (stretched) jpg texture
WAV_RATE = 44100
# Wavs below this rate (or with 8-bit samples) are resampled to WAV_RATE.
MIN_WAV_RATE, MIN_WAV_BITS = 22050, 16
# Longer wavs (jingles, ambient loops) ship as Vorbis; short effects stay PCM.
LONG_SOUND_SECONDS = 2.0


def copy_texture(src: Path, dst: Path) -> None:
    """Copy a texture, stretched to sides that are multiples of the 4x4 compression block:
    WebGL rejects a BC-compressed texture otherwise (the monsters' 1x1 solid-colour skins).
    UVs are normalised, so the stretch keeps the mapping."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as image:
        w, h = image.size
        size = (-(-w // TEXTURE_BLOCK) * TEXTURE_BLOCK, -(-h // TEXTURE_BLOCK) * TEXTURE_BLOCK)
        if size == (w, h):
            shutil.copyfile(src, dst)
            return
        image.resize(size, Image.Resampling.LANCZOS).save(dst, quality=JPEG_QUALITY)


def lua_list(values) -> str:
    return "{" + ", ".join(str(v) for v in values) + "}"


LOCATIONS = range(1, 7)
# The location screen's game objects (main/location/), instanced in every location's
# collection next to its scene.
# The sheets over a location (congratulations, game over, the survival score sheet) hang on the
# camera 10 units in front, drawn by the overlay camera.
SHEET_POSITION = (0.0, 0.0, -10.0)
LOCATION_SCREEN_OBJECTS = [("controller", "/main/location/location.go", None), ("hud", "/main/location/hud.go", None),
                           ("camera", "/main/location/camera.go", None),
                           ("entities", "/generated/entities.go", None),
                           ("congr", "/generated/go/Menu_congr.go", SHEET_POSITION),
                           ("gameover", "/generated/go/Menu_gameover.go", SHEET_POSITION),
                           ("scores", "/generated/go/Menu_Send.go", SHEET_POSITION),
                           ("sel", "/generated/go/Menu_sel.go", SHEET_POSITION),
                           ("ingame", "/generated/go/Menu_ingame.go", SHEET_POSITION),
                           ("ingame_music", "/generated/go/Menu_music.go", SHEET_POSITION),
                           ("ingame_sound", "/generated/go/Menu_sound.go", SHEET_POSITION),
                           ("ingame_sel", "/generated/go/Menu_sel.go", SHEET_POSITION),
                           ("tutorial", "/generated/go/tutorial.go", SHEET_POSITION)]


def lua_str(v: str) -> str:
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_pose(pos, rot) -> str:
    return "{pos = {%s}, rot = {%s}}" % (", ".join(fmt(c) for c in pos), ", ".join(fmt(c) for c in rot))


def lua_rgb(values) -> str:
    return "{%s, %s, %s}" % tuple(fmt(c) for c in values)


class Exporter:
    def __init__(self, import_dir: Path, data_dir: Path, out_dir: Path):
        """`import_dir`: the import stage's tree; `data_dir`: the original's Data/ (sounds)."""
        self.import_dir = import_dir
        self.data_dir = data_dir
        self.out = out_dir
        self.models_dir = import_dir / "assets" / "models"
        self.textures_dir = import_dir / "assets" / "textures"
        self.textures: dict[str, str] = {}
        self.models: dict[str, dict] = {}
        self.location_info = json.loads((import_dir / "data" / "locations.json").read_text())
        self.pass_tags: set[str] = set()   # the order tag of every material exported
        self.placed: set[str] = set()      # models instanced by the screens' collections
        self.links: dict[str, tuple[frozenset[str] | None, list[str]]] = {}  # see resource_links
        self.menus: dict[str, dict] = {}   # menu model key -> pick triangles

    @staticmethod
    def hand_key(location: int, node: str) -> str:
        return f"Location{location}/{node}"

    def node_world(self, glb: Path, name: str):
        """Rest world matrix of node `name` of a scene."""
        exporter = ModelExporter("probe", glb, load_sidecar(glb), self.out, self.textures_dir)
        index = exporter.node_index(name)
        return exporter.world[index]

    def location_glb(self, location: int) -> Path:
        return self.models_dir / f"Location{location}" / f"Location{location}.glb"

    # --- scene light -------------------------------------------------------------------

    def light(self, location: int) -> dict:
        return self.scene_light(self.location_glb(location))

    @staticmethod
    def scene_light(glb: Path) -> dict:
        """Ambient / directional light and background of a scene from its B3DEXT_* tag nodes
        (the sidecar keeps their raw Blitz positions = RGB values)."""
        doc, _ = read_glb(glb)
        scene = (load_sidecar(glb) or {}).get("scene", {})
        ambient = [float(c) for c in scene.get("B3DEXT_AMBIENT", {}).get("pos", [0.5, 0.5, 0.5])]
        bg = [float(c) for c in scene.get("B3DEXT_BGCOLOR", {}).get("pos", [0.0, 0.0, 0.0])]
        dirlight = scene.get("B3DEXT_DIRLIGHT")
        # Blitz has no default light: without a B3DEXT_DIRLIGHT the scene is lit by its
        # ambient and point lights only (the menu).
        color = [0.0, 0.0, 0.0]
        direction = unit_normal((-0.5, -0.8, -0.3))
        if dirlight is not None:
            color = [float(c) for c in dirlight["pos"]]
            # `_fext_initlight`: CreateLight(parent) + TurnEntity 90,0,0 -> the light shines
            # along the parent's -Y (see LocationView._setup_lights / MainMenu.CAMERA_FIX).
            holder = next((n for n in doc["nodes"] if n.get("name") == dirlight["parent"]), None)
            if holder is not None:
                direction = unit_normal(quat_rotate(holder.get("rotation", [0.0, 0.0, 0.0, 1.0]), (0.0, -1.0, 0.0)))
        return {"ambient": ambient, "color": color, "direction": direction, "background": bg,
                "points": point_lights(doc)}

    # --- models --------------------------------------------------------------------------

    def export_model(self, key: str, glb: Path, placed: bool = False, **options) -> ModelExporter:
        """`placed`: the model is an instance in a screen's collection (a location scene, a
        clock hand, a menu sheet or world), never spawned, so it gets no factory."""
        exporter = ModelExporter(key, glb, load_sidecar(glb), self.out, self.textures_dir, **options)
        meta = exporter.run()
        self.textures.update(meta.pop("textures"))
        self.models[key] = meta
        if placed:
            self.placed.add(key)
        self.pass_tags |= {v.tags[0] for v in exporter.variants.values()}
        return exporter

    def export_models(self) -> None:
        for location in LOCATIONS:
            hands = CLOCK_HANDS.get(location, {})
            self.export_model(f"Location{location}", self.location_glb(location), placed=True, exclude_nodes=tuple(hands.values()))
            for node in hands.values():
                self.export_model(self.hand_key(location, node), self.location_glb(location), placed=True, only_node=node)
        for eagle in {e["model"] for e in EAGLE.values()}:
            self.export_model(eagle, self.models_dir / f"{eagle}.glb")
        for name in TOWER_MODELS + TOWER_EXTRAS + BULLET_MODELS:
            self.export_model(f"Towers/{name}", self.models_dir / "Towers" / f"{name}.glb")
        for glb in sorted((self.models_dir / "Monsters").glob("*.glb")):
            if glb.stem == "Health":
                self.export_model("Monsters/Health", glb)
            else:
                self.export_model(f"Monsters/{glb.stem}", glb, lit_default=True)
        for name in ROOT_MODELS:
            self.export_model(name, self.models_dir / f"{name}.glb", hud=name in HUD_MODELS,
                              rank_from=HUD_PANEL_EYE if name == HUD_PANEL else None, anchors=HUD_ANCHORS.get(name))
        self.export_menus()

    def export_menus(self) -> None:
        for key, groups in MENU_SHEETS.items():
            exporter = self.export_model(key, self.models_dir / f"{key}.glb", placed=True, hud=True, posed=True, node_groups=groups,
                                         node_orders=SHEET_ORDERS.get(key), anchors=HUD_ANCHORS.get(key))
            names = [n["name"] for n in exporter.doc["nodes"] if "mesh" in n and "name" in n]
            self.menus[key] = {"pick": exporter.pick_triangles(names)}
        camera = self.export_model(MENU_CAMERA, self.models_dir / f"{MENU_CAMERA}.glb", placed=True, keep_helpers=True)
        scene = (load_sidecar(self.models_dir / f"{MENU_CAMERA}.glb") or {}).get("scene", {})
        fov_h = float(scene.get("B3DEXT_CAMERA", {}).get("pos", [60.0])[0])
        frames = [rigid_pose(mat_mul(m, CAMERA_FIX)) for m in camera.node_world_frames(MENU_CAMERA_NODE)]
        self.menus[MENU_CAMERA] = {"fov_h": fov_h, "frames": frames}
        # The world's translucent nodes are ordered as seen from the main menu's camera.
        for key in MENU_WORLD:
            glb = self.models_dir / f"{key}.glb"
            self.export_model(key, glb, placed=True, posed=True, rank_from=tuple(frames[0][0]))
            self.menus[key] = {"light": self.scene_light(glb)}

    def copy_textures(self) -> None:
        for uri, resource in self.textures.items():
            src = self.textures_dir / Path(resource).relative_to("/assets/textures")
            copy_texture(src, self.out / resource.lstrip("/"))
        # Textures swapped in at runtime.
        for rel in RUNTIME_TEXTURES:
            copy_texture(self.textures_dir / rel, self.out / "assets" / "textures" / rel)
        # Tower bases take the location's ground texture at runtime.
        for location in LOCATIONS:
            copy_texture(self.textures_dir / "Towers" / f"dno{location}.png", self.out / self.ground_texture(location).lstrip("/"))

    @staticmethod
    def ground_texture(location: int) -> str:
        """The tower base (`dno`) texture of a location, set by `_fpositiontower`."""
        return f"/assets/textures/Towers/dno{location}.png"

    # --- zones ---------------------------------------------------------------------------

    def zones(self, location: int) -> dict[str, list[list[float]]]:
        """World-space triangles of the build zones of a location (`CameraPick` targets)."""
        glb = self.location_glb(location)
        exporter = ModelExporter(f"Location{location}", glb, load_sidecar(glb), self.out, self.textures_dir)
        out: dict[str, list[list[float]]] = {}
        nodes = exporter.doc["nodes"]
        for index in exporter.kept:
            node = nodes[index]
            if node.get("name") not in ZONE_NODES or "mesh" not in node:
                continue
            tris = out.setdefault(node["name"], [])
            w = exporter.world[index]
            for prim in exporter.doc["meshes"][node["mesh"]]["primitives"]:
                positions = [transform_point(w, p) for p in read_accessor(exporter.doc, exporter.blob, prim["attributes"]["POSITION"])]
                indices = read_accessor(exporter.doc, exporter.blob, prim["indices"])
                for a, b, c in zip(indices[0::3], indices[1::3], indices[2::3]):
                    tris.append([round(v, 4) for p in (positions[a], positions[b], positions[c]) for v in p])
        return out

    # --- data / audio / hud --------------------------------------------------------------

    def copy_data(self) -> None:
        data_dir = self.out / "data"
        data_dir.mkdir(parents=True, exist_ok=True)
        for name in DATA_FILES:
            shutil.copyfile(self.import_dir / "data" / name, data_dir / name)

    def copy_audio(self) -> list[str]:
        """Encode the original's sounds into assets/audio; returns the shipped file names,
        one per stem."""
        audio_dir = self.out / "assets" / "audio"
        audio_dir.mkdir(parents=True, exist_ok=True)
        names = []
        ffmpeg, oggenc = shutil.which("ffmpeg"), shutil.which("oggenc")
        for name, src in audio_sources(self.data_dir).items():
            stem = Path(name).stem
            if any(Path(n).stem == stem for n in names):
                continue  # menu.wav: the menu.ogg music (sorted first) takes the component id
            wav = src.suffix.lower() == ".wav"
            info = wav_info(src) if wav else None
            if wav and info is None:
                raise ValueError(f"{src}: not a RIFF wav")
            # Most effects are 8 kHz 8-bit; the engine's mixer upsamples them with no
            # filtering and they sound harsh (the rebutton hover). ffmpeg's resampler
            # gives the soft sound the original's DirectSound played.
            rate = WAV_RATE if wav and (info.rate < MIN_WAV_RATE or (info.pcm and info.bits < MIN_WAV_BITS)) else None
            if ffmpeg and oggenc and (not wav or info.seconds > LONG_SOUND_SECONDS):
                # The original's Vorbis streams fail in the engine's web decoder; a plain
                # libvorbis re-encode plays everywhere and keeps the mono music mono.
                dst = audio_dir / f"{stem}.ogg"
                encode_vorbis(src, dst, rate)
            elif ffmpeg and not wav:
                dst = audio_dir / name  # no oggenc: ffmpeg's own Vorbis encoder is stereo only
                encode_ffmpeg_vorbis(src, dst)
            elif ffmpeg and (rate or not info.pcm):
                dst = audio_dir / name
                transcode_wav(src, dst, rate)
            elif wav and not info.pcm:
                raise RuntimeError(f"{src}: a non-PCM wav needs ffmpeg to become PCM")
            else:
                dst = audio_dir / name
                shutil.copyfile(src, dst)
            names.append(dst.name)
        return names

    # --- generated Lua / go ----------------------------------------------------------------

    def used_orders(self, overlay: bool) -> tuple[list[int], list[int]]:
        """EntityOrders used by the exported materials of a layer: positive ones highest
        first, negative ones from -1 down (Blitz draws both with the z-buffer off: the
        positive before everything, the negative after everything, the lowest last)."""
        orders = [o for o in range(-99, 100) if o != 0 and order_tag(o, overlay) in self.pass_tags]
        return sorted([o for o in orders if o > 0], reverse=True), sorted([o for o in orders if o < 0], reverse=True)

    def layer_passes(self, layer: str) -> list[dict]:
        """The translucent passes of the depth layers `<layer>_l0`, `<layer>_l1`, ..."""
        out = []
        rank = 0
        while f"{layer}_l{rank}" in self.pass_tags:
            out += [{"tags": [f"{layer}_l{rank}", cls], "depth_test": True, "depth_write": False, "blend": cls}
                    for cls in ("blend", "add", "mul")]
            rank += 1
        return out

    def resource_file(self, path: str) -> Path | None:
        """A project resource: an exported one (`/generated/`, `/assets/`) from this export
        only, a hand-written one (the screens under main/) from the project; None for a
        builtin."""
        exported = path.startswith(EXPORTED_DIRS)
        candidate = (self.out if exported else PROJECT_DIR) / path.lstrip("/")
        return candidate if candidate.exists() else None

    def resource_links(self, path: str) -> tuple[frozenset[str] | None, list[str]]:
        """A resource's material tags (None unless it is a material) and the resources it
        references, read once per export (the screens share the entities' graph)."""
        if path not in self.links:
            source = self.resource_file(path)
            if source is None or path.endswith(BINARY_RESOURCES):
                self.links[path] = (None, [])
            elif path.endswith(".material"):
                self.links[path] = (frozenset(MATERIAL_TAG.findall(source.read_text())), [])
            else:
                self.links[path] = (None, RESOURCE_REFERENCE.findall(source.read_text()))
        return self.links[path]

    def screen_material_tags(self, collection: str) -> set[frozenset[str]]:
        """The tag sets of every material a screen's collection can draw: its game objects,
        their components and sub-collections, and what its factories spawn."""
        tags: set[frozenset[str]] = set()
        seen: set[str] = set()
        stack = [collection]
        while stack:
            path = stack.pop()
            if path in seen:
                continue
            seen.add(path)
            material, references = self.resource_links(path)
            if material is not None:
                tags.add(material)
            stack += references
        return tags

    def screen_passes(self, world: list[dict], hud: list[dict]) -> dict[str, dict[str, list[int]]]:
        """Per screen (its collection's name): the 1-based indices of the world and HUD passes
        whose predicate some material of the screen matches (all of the pass's tags)."""
        controller = self.resource_file(CONTROLLER_GO)
        out = {}
        for collection in PROXY_COLLECTION.findall(controller.read_text()) if controller else []:
            source = self.resource_file(collection)
            if source is None:
                raise FileNotFoundError(f"{CONTROLLER_GO} loads {collection}, which neither the export nor the project has")
            name = COLLECTION_NAME.search(source.read_text())[1]
            tags = self.screen_material_tags(collection)
            out[name] = {key: [i + 1 for i, p in enumerate(items) if any(set(p["tags"]) <= t for t in tags)]
                         for key, items in (("world", world), ("hud", hud))}
        return out

    def write_render_passes(self) -> None:
        classes = ("opaque", "blend", "add", "mul")

        def unsorted_passes(orders: list[int], overlay: bool) -> list[dict]:
            return [{"tags": [order_tag(o, overlay), cls], "depth_test": False, "depth_write": False, "blend": cls}
                    for o in orders for cls in classes]

        world_first, world_last = self.used_orders(False)
        hud_first, hud_last = self.used_orders(True)
        passes = unsorted_passes(world_first, False)
        # The opaque world writes depth first, then the tower base decals (`dno`) draw on
        # top of it, then the translucent tower bodies. Giving the base its own pass before
        # order_0 blend keeps a translucent trunk from sort-flipping with its own base
        # (which shimmered and shifted colour as the camera moved).
        passes.append({"tags": ["order_0", "opaque"], "depth_test": True, "depth_write": True, "blend": "opaque"})
        # The base decal's opaque (alpha-scissored) footprint writes depth so the underground
        # root is occluded; its blended layers (if any) do not.
        passes.append({"tags": ["base", "opaque"], "depth_test": True, "depth_write": True, "blend": "opaque"})
        for cls in ("blend", "add", "mul"):
            passes.append({"tags": ["base", cls], "depth_test": True, "depth_write": False, "blend": cls})
        # The menu world's translucent nodes in depth layers (MaterialVariant.layer_rank),
        # farthest first, then the unranked translucent brushes.
        passes += self.layer_passes("world")
        for cls in ("blend", "add", "mul"):
            passes.append({"tags": ["order_0", cls], "depth_test": True, "depth_write": False, "blend": cls})
        passes += unsorted_passes(world_last, False)
        hud_passes = unsorted_passes(hud_first, True)
        # The HUD panel's nodes (MaterialVariant.node_rank), farthest first, under the
        # portrait and the sheets.
        hud_passes += self.layer_passes("panel")
        hud_passes += [{"tags": ["hud", cls], "depth_test": True, "depth_write": cls == "opaque", "blend": cls} for cls in classes]
        # The sheets' depth companions (MaterialVariant.solid_variant): depth only.
        hud_passes.append({"tags": ["hud_solid", "opaque"], "depth_test": True, "depth_write": True, "blend": "opaque",
                           "color_write": False})
        # The menu sheets' depth layers (MaterialVariant.layer_rank), farthest first.
        hud_passes += self.layer_passes("hud")
        hud_passes += unsorted_passes(hud_last, True)

        def pass_lines(name: str, items: list[dict]) -> list[str]:
            out = [f"M.{name} = {{"]
            for p in items:
                out.append("    {tags = {%s}, depth_test = %s, depth_write = %s, color_write = %s, blend = \"%s\"}," % (
                    ", ".join(f'"{t}"' for t in p["tags"]), str(p["depth_test"]).lower(), str(p["depth_write"]).lower(),
                    str(p.get("color_write", True)).lower(), p["blend"]))
            return out + ["}"]

        lines = [GENERATED_HEADER,
                 "-- Draw passes of render/blitz.render_script: the union over every exported scene.", "local M = {}", ""]
        lines += pass_lines("world", passes) + pass_lines("hud", hud_passes)
        # A pass no material of the current screen matches still costs a draw command and a
        # render-list lookup every frame: the render script draws only the screen's passes.
        lines += ["", "-- Per screen (its collection's name): the indices of the passes its materials match.",
                  "M.screens = {"]
        for name, lists in sorted(self.screen_passes(passes, hud_passes).items()):
            lines.append('    ["%s"] = {world = {%s}, hud = {%s}},' % (
                name, ", ".join(map(str, lists["world"])), ", ".join(map(str, lists["hud"]))))
        lines += ["}", "", "return M", ""]
        (self.out / "generated" / "render_passes.lua").write_text("\n".join(lines))

    def write_common(self) -> None:
        gradient = export_gradient(self.textures_dir / "Monsters" / "Gradient.bmp", self.out)
        lines = [GENERATED_HEADER, "local M = {}", "",
                 "-- Health bar colours (Gradient.bmp), index 1..100.", "M.gradient = {"]
        lines += ["    %s," % lua_rgb([c / 255.0 for c in rgb]) for rgb in gradient]
        lines += ["}", "", "return M", ""]
        (self.out / "generated" / "common.lua").write_text("\n".join(lines))

    def write_location_data(self, location: int) -> None:
        """generated/locations/l<N>.lua: what the runtime needs to know about a location."""
        loc = self.location_info[str(location)]
        light = self.light(location)
        b = loc["bounds"]
        lines = [GENERATED_HEADER, "local M = {}", "",
                 f"M.location = {location}",
                 "M.bounds = {x_min = %s, x_max = %s, z_min = %s, z_max = %s}" % (b["x_min"], b["x_max"], b["z_min"], b["z_max"]),
                 # `_floadlocation`: CameraClsColor (192, 212, 223) on location 6, black elsewhere.
                 f"M.clear_color = {lua_rgb([c / 255.0 for c in loc['clear_color']])}",
                 "M.light = {dir = %s, color = %s, ambient = %s}" % (lua_rgb(light["direction"]), lua_rgb(light["color"]), lua_rgb(light["ambient"])),
                 f"M.tower_tint = {lua_rgb([c / 255.0 for c in loc['tower_tint_rgb']])}",
                 f"M.shadows = {'true' if loc.get('shadows', True) else 'false'}",
                 f"M.music = {lua_str(Path(loc['music']).stem)}",
                 f"M.first_raid = {loc.get('first_raid', 1)}",
                 "-- Build zones: flat triangle lists (x1, y1, z1, x2, ...) in world space.", "M.zones = {"]
        for zone, tris in self.zones(location).items():
            lines.append(f"    {zone} = {lua_list([v for tri in tris for v in tri])},")
        lines.append("}")
        hands = CLOCK_HANDS.get(location)
        if hands:
            lines.append("-- Clock hands: role -> game object of the location collection.")
            lines.append("M.clock = {%s}" % ", ".join(f'{role} = "clock_{role}"' for role in hands))
        eagle = EAGLE.get(location)
        if eagle:
            glb = self.models_dir / f"{eagle['path']}.glb"
            path_exporter = ModelExporter("probe", glb, load_sidecar(glb), self.out, self.textures_dir)
            frames = [rigid_pose(m) for m in path_exporter.node_world_frames(eagle["node"])]
            lines.append(f"-- The eagle rides node `{eagle['node']}` of {eagle['path']}: pose per frame.")
            lines.append(f'M.eagle = {{model = "{eagle["model"]}", frames = {{')
            for pos, rot in frames:
                lines.append(f"    {lua_pose(pos, rot)},")
            lines.append("}}")
        water = WATER_EMITTER.get(location)
        if water:
            m = self.node_world(self.location_glb(location), water)
            lines.append(f"M.water_emitter = {lua_rgb([m[0][3], m[1][3], m[2][3]])}")
        lines += ["", "return M", ""]
        path = self.out / "generated" / "locations" / f"l{location}.lua"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines))

    def write_locations_index(self) -> None:
        """generated/locations.lua: static requires (bob only bundles modules it can see)."""
        lines = [GENERATED_HEADER, "return {"]
        lines += [f'    [{location}] = require("generated.locations.l{location}"),' for location in LOCATIONS]
        lines += ["}", ""]
        (self.out / "generated" / "locations.lua").write_text("\n".join(lines))

    def write_location_collection(self, location: int) -> None:
        """generated/collections/location<N>.collection, loaded by a collection proxy: the
        location's scene and the location screen's game objects, the controller's
        `location` and ground texture set as overrides. They are top-level overrides on
        purpose: bob does not bundle a resource named only by an override inside a nested
        collection instance."""
        props = [("location", str(location), "PROPERTY_TYPE_NUMBER"), ("ground_texture", self.ground_texture(location), "PROPERTY_TYPE_HASH")]
        lines = [f'name: "location{location}"']
        hands = [(f"clock_{role}", self.models[self.hand_key(location, node)]["go"],
                  tuple(self.node_world(self.location_glb(location), node)[r][3] for r in range(3)))
                 for role, node in CLOCK_HANDS.get(location, {}).items()]
        for ident, prototype, position in [("scene", self.models[f"Location{location}"]["go"], None)] + hands + LOCATION_SCREEN_OBJECTS:
            lines += ["instances {", f'  id: "{ident}"', f'  prototype: "{prototype}"']
            if position:
                lines += ["  position {", f"    x: {position[0]}", f"    y: {position[1]}", f"    z: {position[2]}", "  }"]
            if ident == "controller":
                lines += ["  component_properties {", '    id: "script"']
                for name, value, kind in props:
                    lines += ["    properties {", f'      id: "{name}"', f'      value: "{value}"', f"      type: {kind}", "    }"]
                lines.append("  }")
            lines.append("}")
        lines += ["scale_along_z: 0", ""]
        path = self.out / "generated" / "collections" / f"location{location}.collection"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines))

    def write_menus_lua(self) -> None:
        """generated/menus.lua: per menu sheet the pickable nodes (joint, local triangles);
        the main menu camera's pose per frame (position, rotation) and horizontal fov."""
        lines = [GENERATED_HEADER, "local M = {}", ""]
        for key, menu in self.menus.items():
            lines.append(f'M["{key}"] = {{')
            if "pick" in menu:
                lines.append("    pick = {")
                for name, item in menu["pick"].items():
                    lines.append(f'        ["{name}"] = {{joint = {item["joint"]}, tris = {lua_list(item["tris"])}}},')
                lines.append("    },")
            if "light" in menu:
                light = menu["light"]
                lines.append(f"    clear_color = {lua_rgb(light['background'])},")
                points = ", ".join("{pos = %s, range = %s, color = %s}" % (lua_rgb(pt["position"]), fmt(pt["range"]), lua_rgb(pt["color"]))
                                   for pt in light["points"])
                lines.append("    light = {dir = %s, color = %s, ambient = %s, points = {%s}}," % (
                    lua_rgb(light["direction"]), lua_rgb(light["color"]), lua_rgb(light["ambient"]), points))
            if "frames" in menu:
                lines.append(f"    fov_h = {fmt(menu['fov_h'])},")
                lines.append("    frames = {")
                for pos, rot in menu["frames"]:
                    lines.append(f"        {lua_pose(pos, rot)},")
                lines.append("    },")
            lines.append("}")
        lines += ["", "return M", ""]
        (self.out / "generated" / "menus.lua").write_text("\n".join(lines))

    def write_models_lua(self) -> None:
        lines = [GENERATED_HEADER, "local M = {}", ""]
        for key, meta in self.models.items():
            groups = ", ".join(f"{g} = true" for g in meta["groups"])
            lines.append(f'M["{key}"] = {{')
            # A placed model has no factory (write_entities_go).
            factory = "" if key in self.placed else f'factory = "factory_{key.replace("/", "_")}", '
            lines.append(f'    go = "{meta["go"]}", {factory}frames = {fmt(meta["frames"])}, skinned = {str(meta["skinned"]).lower()},')
            lines.append(f'    morph_targets = {meta["morph_targets"]}, groups = {{{groups}}},')
            if meta.get("bones"):
                b = meta["bones"]
                lines.append(f'    bones = {{count = {b["count"]}, frames = {b["frames"]}, resource = "{b["resource"]}"}},')
            if meta["joints"]:
                joints = ", ".join(f'["{name}"] = {index}' for name, index in meta["joints"].items() if name)
                lines.append(f"    joints = {{{joints}}},")
                lines.append(f"    joint_parents = {lua_list(meta['joint_parents'])},")
            if meta["joint_bounds"]:
                bounds = ", ".join(f"[{j}] = {{{', '.join(fmt(c) for c in box)}}}" for j, box in meta["joint_bounds"].items())
                lines.append(f"    joint_bounds = {{{bounds}}},")
            if meta["frame_atlases"]:
                lines.append("    frame_atlases = {")
                for atlas in meta["frame_atlases"]:
                    lines.append('        {group = "%s", columns = %d, rows = %d, frames = %d, step = %s},' % (
                        atlas["group"], atlas["columns"], atlas["rows"], atlas["frames"], fmt(atlas["step"])))
                lines.append("    },")
            if meta["animmaps"]:
                lines.append("    animmaps = {")
                for m in meta["animmaps"]:
                    keys = ", ".join("{%s, %s}" % (fmt(u), fmt(v)) for u, v in m["keys"])
                    lines.append(f'        {{group = "{m["group"]}", keys = {{{keys}}}}},')
                lines.append("    },")
            lines.append("}")
        lines += ["", "return M", ""]
        (self.out / "generated" / "models.lua").write_text("\n".join(lines))

    def write_entities_go(self) -> None:
        """A factory per spawnable model. A factory keeps its prototype's resources loaded, so
        a placed model (a location scene, the menu's world) would load into every location."""
        lines = []
        for key, meta in self.models.items():
            if key in self.placed:
                continue
            lines += ["embedded_components {", f'  id: "factory_{key.replace("/", "_")}"', '  type: "factory"',
                      f'  data: "prototype: \\"{meta["go"]}\\"\\n"', "}"]
        (self.out / "generated" / "entities.go").write_text("\n".join(lines) + "\n")

    def write_sounds_go(self, names: list[str]) -> None:
        lines = []
        for name in names:
            stem = Path(name).stem
            is_music = stem.startswith("music") or stem == "menu"
            loop = "1" if is_music or stem in LOOPED_SOUNDS else "0"
            group = SOUND_GROUP_MUSIC if is_music else SOUND_GROUP_SFX
            lines += ["embedded_components {", f'  id: "{stem}"', '  type: "sound"',
                      f'  data: "sound: \\"/assets/audio/{name}\\"\\nlooping: {loop}\\ngroup: \\"{group}\\"\\ngain: 1.0\\n"', "}"]
        (self.out / "generated" / "sounds.go").write_text("\n".join(lines) + "\n")

    def run(self) -> None:
        for name in OUTPUT_DIRS:
            shutil.rmtree(self.out / name, ignore_errors=True)
        (self.out / "generated").mkdir(parents=True)
        self.export_models()
        self.copy_textures()
        self.copy_data()
        export_hud_atlas(self.textures_dir / "gui.png", self.out, {"loading": self.textures_dir / "Menu" / "Loading.png"})
        export_icons(self.import_dir / "icons", self.out)
        self.write_common()
        for location in LOCATIONS:
            self.write_location_data(location)
            self.write_location_collection(location)
        self.write_locations_index()
        self.write_menus_lua()
        self.write_models_lua()
        self.write_entities_go()
        self.write_sounds_go(self.copy_audio())
        # Last: the per-screen pass lists read the collections and materials written above.
        self.write_render_passes()
        skinned = sum(1 for m in self.models.values() if m["skinned"])
        LOG.info("%d models (%d skinned), %d textures -> %s", len(self.models), skinned, len(self.textures), self.out)

